default: true

# Enforce max line length for Markdown content
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 0   # ignore code blocks
  tables: false               # ignore tables
  stern: false

# Allow the top level heading in addition to the front matter title
MD025:
  front_matter_title: ""

# Enforce ordered lists by number style
MD029:
  style: ordered

# Require final newline at EOF (consistent with .editorconfig)
MD047: true

