title: "Modern Agile Manifesto"
description: "An AI generated (but human edited and fact checked) manifesto about how to run a modern SaaS company"

# Project site on GitHub Pages
url: "https://kll.github.io"
baseurl: "/modern-agile-manifesto"

markdown: kramdown
highlighter: rouge
permalink: pretty
